### ISSUE TITLE
{'code':1，'msg':'未登录，请重新打开易广金'}

### ISSUE THREAD

**Issue by MOLIzhang** [EastItem/auto-daka#6]

**Comment by babattata-ta** [comment]
遇到同样错误，好像是易广金服务器返回500然后165行出问题了
大佬是不是遇到同样错误了，需要log吗
另外，获取打卡地址的那个URL好像也是500了

**Comment by MOLIzhang** [comment]
> 遇到同样错误，好像是易广金服务器返回500然后165行出问题了 大佬是不是遇到同样错误了，需要log吗 另外，获取打卡地址的那个URL好像也是500了

泪，射了出来  我也没搞懂  等大佬更新吧

**Comment by EastItem** [comment]
已更新
