### ISSUE TITLE
求教:uuid填什么？

### ISSUE THREAD

**Issue by mark-yjx** [EastItem/auto-daka#8]
@EastItem

**Comment by mark-yjx** [comment]
stream只能抓到loginToken

**Comment by MOLIzhang** [comment]
> stream只能抓到loginToken

检查一下ssl证书有没有安装，这边测试过还是可以抓到。
btw 这个项目6月3号后就用不了了 等作者更新吧

**Comment by mark-yjx** [comment]
> 
请问SSL证书怎么安装？
stream开始抓包后再点易广金就会显示 `An SSL error has occurred and a secure connection to the server cannot be made.`
我原来用的是[https://github.com/liangzejun123/GDUF_autocheck](url) 也是6月3号之后就用不了了

**Comment by mark-yjx** [comment]
> 
stream开始抓包后再点易广金就会显示 `An SSL error has occurred and a secure connection to the server cannot be made.`
我原来用的是[https://github.com/liangzejun123/GDUF_autocheck](url) 确实也是6月3号就用不了了

**Comment by MOLIzhang** [comment]
怪 我这边stream能正常抓包

**Comment by mark-yjx** [comment]
> 怪 我这边stream能正常抓包

stream开始抓包后能进易广金吗？

**Comment by babattata-ta** [comment]
> > 怪 我这边stream能正常抓包
> 
> stream开始抓包后能进易广金吗？

可以，你确定安装了HTTPS证书和先打开易班再抓包？

**Comment by mark-yjx** [comment]
> > > 怪 我这边stream能正常抓包
> > 
> > 
> > stream开始抓包后能进易广金吗？
> 
> 可以，你确定安装了HTTPS证书和先打开易班再抓包？

确定，易班版本是5.0.10

**Comment by mark-yjx** [comment]
![89c6776cf34b65980bd2f033d8a376c](https://user-images.githubusercontent.com/69899898/174737764-224cb381-5570-4962-bc30-4ef6d4b1c5c2.jpg)
![79ba6cf9f5a6dcf74ffcc51a7995810](https://user-images.githubusercontent.com/69899898/174737781-86b918fb-c9d3-42fc-a8aa-d30ee3d2f033.jpg)

**Comment by cyugwan** [comment]
尝试过重新安装易班和stream以及证书吗？
我也曾遇到过这个问题，但是他自己就好了
而且无法复现

**Comment by babattata-ta** [comment]
刚才试了一下，你确认下你信任证书了吗

在stream——https抓包里是否显示CA证书已经安装且信任

如果没有，则到设置——通用——关于本机——证书信任设置勾上stream证书

**Comment by mark-yjx** [comment]
> 刚才试了一下，你确认下你信任证书了吗
> 
> 在stream——https抓包里是否显示CA证书已经安装且信任
> 
> 如果没有，则到设置——通用——关于本机——证书信任设置勾上stream证书

重装了stream和易班就可以正常工作了，感谢大佬指导
